# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytania', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupa',
            name='token',
            field=models.CharField(help_text='Hasło dostępu do grupy testowej', max_length=128, verbose_name='Hasło grupy'),
        ),
    ]
