# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pytania', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrazek',
            name='kategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='obrazki', to='pytania.Kategoria'),
        ),
        migrations.AlterField(
            model_name='obrazek',
            name='opis',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='opis obrazka'),
        ),
    ]
