# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pytania', '0002_auto_20170511_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrazek',
            name='autor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
